name: Daily Build and Publish

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual invocation

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: playcanvas/editor-api

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: "@smth-for"

      - name: Create .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@smth-for:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Change package.json name
        run: |
          jq '.name = "@${{ github.repository }}"' package.json > tmp.$$.json && mv tmp.$$.json package.json

      - name: Get package version
        id: get-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Check if package version is already published
        id: check-published
        run: |
          if npm view @${{ github.repository }}@${{ steps.get-version.outputs.version }} version > /dev/null 2>&1; then
            echo "Package version ${{ steps.get-version.outputs.version }} is already published."
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "Package version ${{ steps.get-version.outputs.version }} is not published yet."
            echo "published=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check-published.outputs.published == 'false'
        run: npm install

      - name: Build package
        if: steps.check-published.outputs.published == 'false'
        run: npm run build

      - name: Publish to GitHub Package Registry
        if: steps.check-published.outputs.published == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
